
export const Users =[
    {
        id : 1,
        profilePicture:"/assets/img/1.jpeg",
        username: 'Nguyễn Ngọc Thắng',
    },
    {
        id : 2,
        profilePicture:"/assets/img/2.jpeg",
        username: 'Nguyễn Quốc Anh',
    },
    {
        id : 3,
        profilePicture:"/assets/img/4.jpeg",
        username: 'Trần Hồng Quân',
    },
    {
        id : 4,
        profilePicture:"/assets/img/5.jpeg",
        username: 'Hướng Hoà',
    },
    {
        id : 5,
        profilePicture:"/assets/img/6.jpeg",
        username: 'Đỗ Mỹ Tài',
    },
    {
        id : 6,
        profilePicture:"/assets/img/20IT347.jpeg",
        username: 'Phan Văn CẸC',
    },
    {
        id : 9,
        profilePicture:"/assets/img/4.jpeg",
        username: 'Trần Hồng Quân',
    },
    {
        id : 34,
        profilePicture:"/assets/img/5.jpeg",
        username: 'Hướng Hoà',
    },
    {
        id : 53,
        profilePicture:"/assets/img/6.jpeg",
        username: 'Đỗ Mỹ Tài',
    },
    {
        id : 62,
        profilePicture:"/assets/img/20IT347.jpeg",
        username: 'Phan Văn CẸC',
    },
    {
        id : 7,
        profilePicture:"/assets/img/5.jpeg",
        username: 'Hướng Hoà',
    },
    {
        id : 8,
        profilePicture:"/assets/img/6.jpeg",
        username: 'Đỗ Mỹ Tài',
    },
];
export const Posts = [
    {
        id : 1,
        desc:"Love For All , Hatred for None,",
        photo:"/assets/img/1.jpeg",
        date:"5 phút Trước",
        userId:1,
        like: 32,
        comment: 9,
        share:20,
    },
    {
        id : 2,
        desc:"yêu chó cưng nên đang lên cho mọi người biết chó của mình đẹp như nào,",
        photo:"/assets/img/2.jpeg",
        date:"54 phút Trước",
        userId:2,
        like: 12,
        comment: 6,
        share:27,
    },
    {
        id : 3,
        desc:"hôm nay ngày 20 -10 mình đăng ảnh chó này lên tặng cho các bạn nữ nhân ngày lễ nha",
        photo:"/assets/img/13.jpeg",
        date:"14 phút Trước",
        userId:3,
        like: 67,
        comment: 19,
        share:203,
    },
    {
        id : 4,
        desc:"các bạn nam đã có quà gì tặng các bạn gái chưa mình có con chó nè !,",
        photo:"/assets/img/4.jpeg",
        date:"48 phút Trước",
        userId:4,
        like: 326,
        comment: 99,
        share:203,
    },

    {
        id : 5,
        desc:" xin chào các bạn mình đã trở lại với hozzal nè",
        photo:"assets/img/5.jpeg",
        date:"43 phút Trước",
        userId:5,
        like: 342,
        comment: 119,
        share:220,
    },{
        id : 6,
        desc:"Love For All , Hatred for None,",
        photo:"/assets/img/11.png",
        date:"15 phút Trước",
        userId:6,
        like: 3247,
        comment: 943,
        share:320,
    },
    {
        id : 7,
        desc:"Love For All , Hatred for None,",
        photo:"/assets/img/8.jpeg",
        date:"53 phút Trước",
        userId:7,
        like: 245,
        comment: 219,
        share:270,
    },
    {
        id : 8,
        desc:"Love For All , Hatred for None,",
        photo:"/assets/img/7.jpeg",
        date:"25 phút Trước",
        userId:8,
        like: 312,
        comment:29,
        share:2,
    },
];
    